{% set name = "whois" %}
{% set version = "5.5.17" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: http://ftp.debian.org/debian/pool/main/w/whois/whois_{{ version }}.tar.xz
  sha256: effe86e6d75101c2f33a0b3d2d948ab54aa57893fedc3b9983ffd55e881e2521
  patches:
    - Makefile.patch  # [osx]

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - make
    - pkg-config
  host:
    - libidn2
    - libiconv
  run:
    - libidn2

test:
  commands:
    - whois --help
    - mkpasswd --help

about:
  home: https://github.com/rfc1036/whois
  license: GPL-2.0
  license_family: GPL
  license_file: COPYING
  summary: Intelligent WHOIS client
  dev_url: https://github.com/rfc1036/whois

extra:
  recipe-maintainers:
    - scopatz
