{% set name = "whois" %}
{% set version = "5.5.18" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: http://ftp.debian.org/debian/pool/main/w/whois/whois_{{ version }}.tar.xz
  sha256: 80132ac952e882fc2b1e8e681e9a0d432949f99afa7503d257487515c85cd5b8
  patches:
    - Makefile.patch  # [osx]

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - make
    - pkg-config
  host:
    - libidn2
    - libiconv
  run:
    - libidn2

test:
  commands:
    - whois --help
    - mkpasswd --help

about:
  home: https://github.com/rfc1036/whois
  license: GPL-2.0
  license_family: GPL
  license_file: COPYING
  summary: Intelligent WHOIS client
  dev_url: https://github.com/rfc1036/whois

extra:
  recipe-maintainers:
    - scopatz
